application: angularjs-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: (.*)/
  static_files: src\1/index.html
  upload: app

- url: (.*)
  static_files: src\1
  upload: app